feat(search-input): add clear button at search
bampakoa/angular-heroes pull request #13
Opened 2021-05-14 13:43 UTC by nikosanif

#### Changelog:
- Add clear button as input suffix
- Add tests for clear button

2021-05-14 13:46 UTC, nikosanif commented
Hi @bampakoa ! Awesome work!

I made a pull request adding a clear button at main search input. I'll be happy if you can review and merge it. Feel free to refactor the code and make any required changes.

2021-05-14 19:34 UTC, bampakoa commented
@nikosanif thanks very much for your PR 🙏 I would be more than happy to review it.

Could you please first make sure that your editor has not done any formatting changes that are not related to the feature? Thanks!

2021-05-15 11:19 UTC, nikosanif commented
Thanks for the advice @bampakoa! I have reverted all formatting changes. I was using `Prettier` as code formatter. Do you use any specific formatter or you use the defaults from `.editorconfig`?

2021-05-17 19:05 UTC, bampakoa reviewed
@nikosanif I think that the tests for the clear button are not necessary since we are not interacting with the component class. Let me elaborate a bit on this:

The `searchBox` variable is a [template reference variable ](https://angular.io/guide/template-reference-variables) that is present only in the template of the component. It does not interact with a property in the TypeScript class of the component. Thus, these types of tests seem to be a better fit for e2e tests 😉

2021-05-17 19:07 UTC, bampakoa commented
I am a fan of the default configuration generally 😁 so, yes, I use the ones from the `.editorconfig` (for now).

2021-05-18 05:51 UTC, nikosanif commented
> @nikosanif I think that the tests for the clear button are not necessary since we are not interacting with the component class. Let me elaborate a bit on this:
> 
> The `searchBox` variable is a [template reference variable ](https://angular.io/guide/template-reference-variables) that is present only in the template of the component. It does not interact with a property in the TypeScript class of the component. Thus, these types of tests seem to be a better fit for e2e tests 😉 

Another good advice for me 😁! I don't have much experience about tests so your statement it's very useful. 

Do think that it's better to remove them completely?

2021-05-18 07:17 UTC, nikosanif commented on src/app/characters/character-list/character-list.component.html
> +        </button>
Yep, I changed it to single line.

2021-05-19 10:50 UTC, bampakoa commented
>Do think that it's better to remove them completely?

If you can, that would be great. We can add it back l8r when starting to write e2e tests 😃

2021-05-19 14:39 UTC, bampakoa requested changes
@nikosanif just a minor change and we are good to go 😃

2021-05-19 14:39 UTC, bampakoa commented on src/app/characters/character-list/character-list.component.html
> +        <button *ngIf="searchBox?.value" mat-button matSuffix mat-icon-button aria-label="Clear" (click)="searchBox.value = ''">
```suggestion
        <button *ngIf="searchBox?.value" matSuffix mat-icon-button aria-label="Clear" (click)="searchBox.value = ''">
```

2021-05-19 14:49 UTC, nikosanif commented on src/app/characters/character-list/character-list.component.html
> +        <button *ngIf="searchBox?.value" mat-button matSuffix mat-icon-button aria-label="Clear" (click)="searchBox.value = ''">
Nice catch! I didn't see that.

2021-05-19 15:55 UTC, bampakoa approved these changes

2021-05-19 15:56 UTC, merged